# Generated by Django 2.1.2 on 2018-10-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'permissions': (('commenter_article', 'Commenter un article'), ('marquer_article', 'Marquer un article comme lu')), 'verbose_name': 'article'},
        ),
    ]
