# Generated by Django 2.1.2 on 2018-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0002_auto_20181012_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniurl',
            name='url_longue',
        ),
        migrations.AddField(
            model_name='miniurl',
            name='url',
            field=models.URLField(default='http://www.perdu.com', unique=True, verbose_name='URL à réduire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='nombre_acces',
            field=models.IntegerField(default=0, verbose_name="Nombre d'accès à l'URL"),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='pseudo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
