# Generated by Django 2.1.2 on 2018-10-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0003_auto_20181012_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniurl',
            options={'verbose_name': 'Mini URL', 'verbose_name_plural': 'Minis URL'},
        ),
    ]
